/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.Vistas.Jugador;

import Logica.Jugador;
import Logica.JugadorMesa;
import Logica.Mesa;
import Presentacion.Controladores.MesasDisponiblesControlador;
import Presentacion.Interfaces.MesasDisponiblesInterface;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;

/**
 *
 * @author sofia
 */
public class MesasDisponiblesVentana extends javax.swing.JFrame implements MesasDisponiblesInterface {
    
    private MesasDisponiblesControlador controlador;
    private Mesa mesaSeleccionada; 
    /**
     * Creates new form MesasDisponibles
     */
    public MesasDisponiblesVentana( Jugador jugador) {
        initComponents();
        this.setTitle("Aplicacion Jugador - Unirse a mesa "); //Preguntar 
        this.controlador = new MesasDisponiblesControlador(jugador, this);
        listMesasDisponibles.setCellRenderer(new MesasRenderer());      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnUnirse = new javax.swing.JButton();
        btnLogOff = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMesasDisponibles = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mesas abiertas");

        btnUnirse.setBackground(new java.awt.Color(204, 255, 204));
        btnUnirse.setForeground(new java.awt.Color(0, 0, 0));
        btnUnirse.setText("Unirse");
        btnUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseActionPerformed(evt);
            }
        });

        btnLogOff.setBackground(new java.awt.Color(255, 51, 51));
        btnLogOff.setForeground(new java.awt.Color(0, 0, 0));
        btnLogOff.setText("Log Off");
        btnLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOffActionPerformed(evt);
            }
        });

        listMesasDisponibles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listMesasDisponibles.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listMesasDisponiblesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listMesasDisponibles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed
        this.unirse();
    }//GEN-LAST:event_btnUnirseActionPerformed

    private void btnLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOffActionPerformed

    private void listMesasDisponiblesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listMesasDisponiblesValueChanged
        mesaSeleccionada = (Mesa) listMesasDisponibles.getSelectedValue();
    }//GEN-LAST:event_listMesasDisponiblesValueChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOff;
    private javax.swing.JButton btnUnirse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listMesasDisponibles;
    // End of variables declaration//GEN-END:variables

    private void unirse() {
        controlador.unirseMesa(mesaSeleccionada);
    }

    @Override
    public void hidratarLista(List<Mesa> mesas) {
         listMesasDisponibles.setListData(mesas.toArray());
    }

    @Override
    public void siguienteVentana(JugadorMesa jm) {
        JOptionPane.showMessageDialog(this, "HOLA MUNDO" + jm.getMesa());
    }
    
    
    
    private class MesasRenderer extends JLabel implements ListCellRenderer<Mesa> {
        
        @Override
        public Component getListCellRendererComponent(JList list, Mesa mesa, int index, boolean isSelected, boolean cellHasFocus) {
            
            this.setText("Mesa: "  + mesa.getIdMesa() + "-" + " Balance: " + mesa.getBalance() + "-");// + " Crupier: " + mesa.getCrupier().getNombreCompleto());
            if (isSelected) {
                this.setBackground(Color.BLUE);
            }
            return this;
            
            
        }
    }
    
}
