/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.Vistas.Crupier;

import Logica.Crupier;
import Logica.Mesa;
import Logica.TipoApuesta;
import Presentacion.Controladores.ConfigurarMesaControlador;
import Presentacion.Interfaces.ConfigurarMesaInterface;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.ListCellRenderer;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;

/**
 *
 * @author sofia
 */
public class ConfigurarMesaVentana extends javax.swing.JFrame implements ConfigurarMesaInterface {
    
    private ConfigurarMesaControlador controlador;
    private List<TipoApuesta> habilitados;

    /**
     * Creates new form ConfigurarMesaVentana
     */
    public ConfigurarMesaVentana(Crupier crupier) {
        initComponents();
        this.controlador= new ConfigurarMesaControlador(crupier,this);
        jList1.setCellRenderer(new TiposRenderer()); // Set custom cell renderer
        jList1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION); // Allow multiple selections
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Selecciona los tipos de apuesta");

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.configurarMesa();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
       habilitados = jList1.getSelectedValuesList();
    }//GEN-LAST:event_jList1ValueChanged

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void hidratarLista(List<TipoApuesta> tipos){
        jList1.setListData(tipos.toArray());
        jList1.setSelectedIndex(0);
        
    }
    
    public void configurarMesa(){
        controlador.configurarMesa(habilitados);
        //JOptionPane.showMessageDialog(this, habilitados);
    }
    
    
    @Override
    public void siguienteVentana(Crupier crupier){
        new MesaCrupierVentana(crupier).setVisible(true);
        this.disable();
}
    
    private class TiposRenderer extends JPanel  implements ListCellRenderer<TipoApuesta> {
        private JLabel label;
        private JCheckBox checkBox;

        public TiposRenderer() {
             setLayout(new BorderLayout());

            label = new JLabel();
            add(label, BorderLayout.CENTER);

            checkBox = new JCheckBox();
            checkBox.setHorizontalAlignment(SwingConstants.CENTER);

            add(checkBox, BorderLayout.WEST);
        }
        
        @Override
        public Component getListCellRendererComponent(JList list, TipoApuesta tipos, int index, boolean isSelected, boolean cellHasFocus) {
        label.setText(tipos.getNombre());
        checkBox.setSelected(isSelected);
        setEnabled(list.isEnabled());
        setComponentOrientation(list.getComponentOrientation());
        setFont(list.getFont());
        return this;  
        }
        
       
        
    }
    

    
    
    
    

}
